services:
  - type: static
    name: blackjack-game-client
    env: static
    staticPublishPath: dist
    routes:
      - path: /sitemap.xml
        serve: /sitemap.xml
      - path: /*
        rewrite: /index.html